### PR TITLE
First step towards generating packages

### PR DESCRIPTION
**Pull request by mamhoff**
This will generate a directory `packages` with directories for every methodology, each with `data.json` and `itemDefinitions.json` files. 

run 
```sh
node src/generatePackage.js
``` 
to try out.

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Hey @mamhoff can you let me know which version of node you're using?

I'm getting this error when I run this, and I wonder if there's dataset that's not confirming:

```
node src/generatePackage.js

(node:73397) ExperimentalWarning: The fs.promises API is experimental

/Users/chrisadams/Code/openamee/datasets/src/convertData.js:35
      } else if (itemDefinitions[header].type === "DECIMAL") {
                                         ^

TypeError: Cannot read property 'type' of undefined
    at CsvParser.mapValues (/Users/chrisadams/Code/openamee/datasets/src/convertData.js:35:42)
    at mapValue (/Users/chrisadams/Code/openamee/datasets/node_modules/csv-parser/index.js:152:19)
    at CsvParser._online (/Users/chrisadams/Code/openamee/datasets/node_modules/csv-parser/index.js:170:17)
    at CsvParser._transform (/Users/chrisadams/Code/openamee/datasets/node_modules/csv-parser/index.js:258:16)
    at CsvParser.Transform._read (_stream_transform.js:190:10)
    at CsvParser.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at CsvParser.Writable.write (_stream_writable.js:294:11)
    at Readable.ondata (_stream_readable.js:689:20)
```

Is this related here when you created the issue for `transport/van/generic/itemdef.csv` ?

https://github.com/thegreenwebfoundation/datasets/issues/15

**Comment by mamhoff** [comment]
I'm using node 12, maybe we should switch down to 10?

**Comment by mrchrisadams** [comment]
Summarising from another convo.

If we have the try-catch block this should work.

I'm in favour of us having a short-lived branch, and later updating this to programatically generate the package.json files, we'd need to make all these individually installable in another issue.

👍  ?

**Comment by mamhoff** [comment]
I've added another commit to make the CSV parsing more resilient, and added issue #17 so that we can deal with that `units` issue lateron. 

The code does run with Node 10, it just issues that warning about `fs.promises` being experimental. Since we live in the future we know that it'll just work in future node versions such as 12 -> not changing anything. :)

**Comment by mrchrisadams** [comment]
Nice, this totally worked at my end. Merging in. Thanks Martin!

**Pull request merged**
